[package]
name = "jsonrs"
version = "0.2.1"
authors = []
edition = "2018"

[lib]
name = "jsonrs"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
flate2 = { version = "1.0" }
rustler = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_rustler = { git = "https://github.com/benhaney/serde_rustler", tag = "v0.0.6" }
serde-transcode = "1.1"
lazy_static = "1.0"
